sonar.projectKey=starci-skills-fe
sonar.projectName=StarCi Skills Console
sonar.host.url=https://sonar.starci.org
sonar.qualitygate.wait=true
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
