import type {ProjectState, RegistryEntry} from "@/types"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {ScrollArea} from "@/components/ui/scroll-area"
import {Separator} from "@/components/ui/separator"
import {Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger} from "@/components/ui/sheet"
import {Verdict} from "@/components/verdict"
import {Heading} from "@/components/leaves/Heading"
import {panelBreakMonoClassName, panelBreakMutedClassName, panelDecisionListClassName, panelDecisionRowClassName, panelFlexWrapClassName, panelMapEntryClassName, panelMapPreClassName, panelRoundCardClassName, panelSectionClassName, panelSectionTextClassName, panelSessionBodyClassName, panelSmallMutedClassName, panelStackClassName, panelStackTightClassName} from "@/panels/classNames"
import {panelCopy} from "@/resources/panelCopy"

const stateTone = {queued: "warn", approved: "ok", rejected: "bad"} as const
type EntryProps = {entry: RegistryEntry}
type SectionProps = {title: string; fact?: string; children: React.ReactNode}
type RegistryDetailProps = {project: ProjectState}
const Entry = (props: EntryProps) => <div className={panelRoundCardClassName}><div className={panelStackClassName}><span className={panelBreakMonoClassName}>{props.entry.file}</span><Verdict tone={stateTone[props.entry.state]}>{props.entry.state}</Verdict></div><div className={panelBreakMutedClassName}>{props.entry.surface ? <span>surface {props.entry.surface}</span> : null}{props.entry.members !== null ? <span>{props.entry.members} candidate</span> : null}<span>{(props.entry.bytes / 1024).toFixed(1)} KB</span><span>{props.entry.changedAt.replace("T", " ").slice(0, 19)}</span></div>{props.entry.hash ? <span className={panelBreakMutedClassName}>{props.entry.hash}</span> : null}</div>
const Section = (props: SectionProps) => <section className={panelSectionClassName}><div className={panelStackClassName}><Heading level={3} content={props.title} />{props.fact ? <span className={panelSmallMutedClassName}>{props.fact}</span> : null}</div>{props.children}</section>

/** Renders one project's registry details and append-only decisions. */
export const RegistryDetail = (props: RegistryDetailProps) => {
    const registry = props.project.registry
    const kinds = ["layouts", "blocks"] as const
    return <Sheet><SheetTrigger render={<Button variant="outline" size="sm" />}>{panelCopy.details}</SheetTrigger><SheetContent><div className="w-full sm:max-w-xl"><SheetHeader><SheetTitle>{props.project.project}</SheetTitle><SheetDescription>{props.project.root}</SheetDescription></SheetHeader><ScrollArea><div className={panelSessionBodyClassName}><Section title={panelCopy.roots}><div className={panelFlexWrapClassName}>{(["registries", "sessions", "cache"] as const).map((key) => <Verdict key={key} tone={props.project.roots[key] ? "ok" : "warn"}>{key}</Verdict>)}</div></Section><Separator />{registry ? <><Section title={panelCopy.registry}><div className={panelSectionTextClassName}><div className={panelFlexWrapClassName}><Verdict tone={registry.locked ? "ok" : "bad"}>{registry.locked ? "locked" : "unlocked"}</Verdict><Verdict tone={registry.clean ? "ok" : "bad"}>{registry.clean ? "clean" : "dirty"}</Verdict><Verdict tone={registry.ownedHere ? "ok" : "bad"}>{registry.ownedHere ? "owned here" : "foreign git"}</Verdict></div><span className={panelBreakMutedClassName}>{registry.branch ?? "—"}</span><span className={panelSmallMutedClassName}>{registry.head ?? "—"}</span></div></Section>{kinds.map((kind) => { const rows = (registry.entries ?? []).filter((entry) => entry.kind === kind); return <Section key={kind} title={kind} fact={`${rows.length} artifact`}>{rows.length === 0 ? <p className={panelSmallMutedClassName}>No recorded {kind}.</p> : <div className={panelStackTightClassName}>{rows.map((entry) => <Entry key={`${entry.kind}/${entry.state}/${entry.file}`} entry={entry} />)}</div>}</Section>})}<Section title="Map" fact={`${(registry.maps ?? []).length} file`}>{(registry.maps ?? []).length === 0 ? <p className={panelSmallMutedClassName}>No registry index.</p> : (registry.maps ?? []).map((map) => <div key={`${map.kind}/${map.file}`} className={panelMapEntryClassName}><span className={panelBreakMutedClassName}>{map.kind}/map/{map.file}</span><pre className={panelMapPreClassName}>{JSON.stringify(map.content, null, 2)}</pre></div>)}</Section><Section title="Decisions & rejections"><div className={panelDecisionRowClassName}><Badge variant="outline">{(registry.decisions ?? []).length} decision</Badge><Badge variant="outline">{(registry.rejections ?? []).length} rejection</Badge></div>{(registry.decisions ?? []).length + (registry.rejections ?? []).length === 0 ? <p className={panelSmallMutedClassName}>No records.</p> : <ul className={panelDecisionListClassName}>{[...(registry.decisions ?? []), ...(registry.rejections ?? [])].map((fact) => <li key={fact}>{fact}</li>)}</ul>}</Section></> : <p className={panelSmallMutedClassName}>This project has no registry.</p>}</div></ScrollArea></div></SheetContent></Sheet>
}
