import type {Round, SessionState} from "@/types"
import {Button} from "@/components/ui/button"
import {ScrollArea} from "@/components/ui/scroll-area"
import {Separator} from "@/components/ui/separator"
import {Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger} from "@/components/ui/sheet"
import {CopyCommand, Verdict} from "@/components/verdict"
import {Heading} from "@/components/leaves/Heading"
import {panelAmberTextClassName, panelBreakMonoClassName, panelFlexWrapClassName, panelItalicMutedClassName, panelMutedTextClassName, panelRefusalLabelClassName, panelRejectedClassName, panelRoundCardClassName, panelSectionClassName, panelSessionBodyClassName, panelSmallMutedClassName, panelStackClassName, panelStackTightClassName, panelGreenTextClassName} from "@/panels/classNames"
import {panelCopy} from "@/resources/panelCopy"
const roundTone = {accepted: "ok", feedback: "warn", pending: "idle"} as const
type RoundCardProps = {round: Round}
type SessionDetailProps = {session: SessionState; project: string}
const RoundCard = (props: RoundCardProps) => <div className={panelRoundCardClassName}><div className={panelStackClassName}><span className={panelSmallMutedClassName}>Round {props.round.number} {props.round.phase}</span><Verdict tone={roundTone[props.round.state]}>{props.round.state}</Verdict></div>{props.round.prompt ? <p className={panelSmallMutedClassName}>{props.round.prompt}</p> : null}{props.round.produced.length > 0 ? <div className={panelStackTightClassName}><span className={panelSmallMutedClassName}>Produced</span>{props.round.produced.map((item) => <div key={item.hash} className={panelFlexWrapClassName}><span className={props.round.acceptedHash === item.hash ? panelGreenTextClassName : panelMutedTextClassName}>{item.hash.slice(0, 12)}…</span><span className={panelSmallMutedClassName}>{item.id}</span></div>)}</div> : null}{props.round.refusal ? <div className={panelStackTightClassName}><span className={panelRefusalLabelClassName}>returned-to-owner</span><span className={panelSmallMutedClassName}>{props.round.refusal}</span></div> : null}{props.round.rejected.length > 0 ? <div className={panelStackTightClassName}><span className={panelSmallMutedClassName}>Rejected</span>{props.round.rejected.map((item) => <div key={item.hash} className={panelRejectedClassName}><span className={panelBreakMonoClassName}>{item.hash.slice(0, 12)}…</span><span className={panelItalicMutedClassName}>{item.reason}</span></div>)}</div> : null}</div>

/** Renders the append-only history and queued hashes for one session. */
export const SessionDetail = (props: SessionDetailProps) => { const queued = props.session.queued.filter((item) => item.state === "queued"); return <Sheet><SheetTrigger render={<Button variant="outline" size="sm" />}>{panelCopy.details}</SheetTrigger><SheetContent><SheetHeader><SheetTitle>{props.session.surface}</SheetTitle><SheetDescription>{props.project} · phase {props.session.phase} · {props.session.rounds} rounds<span>{props.session.file}</span></SheetDescription></SheetHeader><ScrollArea><div className={panelSessionBodyClassName}>{queued.length > 0 ? <><section className={panelSectionClassName}><Heading level={3} content={panelCopy.waiting} />{queued.map((item) => <div key={item.hash} className={panelStackTightClassName}><span className={panelAmberTextClassName}>{item.hash}</span><span className={panelSmallMutedClassName}>{item.phase}</span></div>)}<CopyCommand command={`/starci-fe-design-${props.session.phase} ${props.session.surface}`} /></section><Separator /></> : null}<section className={panelSectionClassName}><Heading level={3} content={panelCopy.history} />{props.session.history.length === 0 ? <p className={panelSmallMutedClassName}>{panelCopy.noHistory}</p> : props.session.history.map((round) => <RoundCard key={round.number} round={round} />)}</section></div></ScrollArea></SheetContent></Sheet> }
